version: '3.8'

services:
  backend:
    container_name: backend
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
  
  redis:
    container_name: redis
    image: redis
    ports:
      - "6380:6379"
  
  celery:
    container_name: celery
    build: .
    command: celery -A app.celery_config.celery_app worker -l info
    env_file:
      - .env
    depends_on:
      - redis
  
  celery_beat:
    container_name: celery_beat
    build: .
    command: celery -A app.celery_config.celery_app beat -l info
    env_file:
      - .env
    depends_on:
      - redis

  flower:
    container_name: flower
    build: .
    command: celery -A app.celery_config.celery_app flower
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery
